# Generated by Django 5.1.4 on 2025-01-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_Link',
            new_name='demo_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='source_Link',
            new_name='source_link',
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
